### PR TITLE
Landing Page Styles

### PR DESCRIPTION
**Pull request by groov1234**
# Description

Adds Hero image to CompanyRegister page. Cleans up some styling inheritance issues. And removes a few unnecessary variables from various components.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

company
user

### CODE REVIEW

**Comment by groov1234** [comment]
Oh, thank you for adding that back. That was the one I removed trying to fix a margin issue and forgot to add it back in.

**Comment by masontmorrow** [comment]
Do the forms have different widths? I can't tell from the screen shot. If they do, try to make sure they both have the same CSS rule applied to them for easy editing across the app.

**Comment by groov1234** [comment]
I'm trying to figure that one out right now. The width changed due to a change in the flex rule. `flex: 1 1` became `flex: 6 1` and `flex: 3 1` to get the background image sized properly. I'll commit as soon as I get them matching more perfectly.

**Comment by masontmorrow** [comment]
Hmm, I'll pull up the Netlify preview to see what I can do. The `flex` property can be very dangerous lol.

**Comment by groov1234** [comment]
the widths match now.

**Comment by groov1234** [comment]
Looking into that now

**Comment by groov1234** [comment]
The main issue is probably that we haven't yet added any media queries. If we can get the desktop view to an approved setup we can work on getting the sizing right at other media sizes.

**Comment by masontmorrow** [comment]
Hmm, no this isn't a media-query problem. (We can work on that later for mobile stuff). This is a flexbox problem mixed with hardcoded pixel sizes used in the margin / duplicate class functions. I'm going to pull this branch and rework it and make a push to it. I think you can just add one line of code to accomplish what you are trying to accomplish.

**Comment by bdurb** [comment]
Nice job working through this.  merging PR.

**Pull request merged**
