### PR TITLE
set up jobpost api endpoints

### PR DESCRIPTION
**Pull request by dk574**
# Description

Set up job post api endpoints to prep for frontend. No errors so far. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

screen shot 2018-09-14 at 11 27 39 am

screen shot 2018-09-14 at 11 28 25 am

screen shot 2018-09-14 at 11 28 08 am

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by groov1234** [comment]
We'll need a tags section I believe as well

**Comment by dk574** [comment]
Thanks @groov1234! Yeah, I'm working on those to be fixed first before this can be merged. I'm trying to get the createsuperuser to work to test again after pulling recent changes.

**Comment by bdurb** [comment]
Excellent testing documentation.  Great work.  Merging PR.

**Comment by bdurb** [comment]
Due to environment issues, closing this pull request.

**Pull request closed without merging**
